# Generated by Django 5.1.4 on 2024-12-10 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Establishments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('direction', models.TextField()),
                ('link_google_maps', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('link_google_maps', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('document_id', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('phone', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
                ('image', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='events_establishments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpoturapp.establishments')),
                ('id_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpoturapp.events')),
            ],
        ),
        migrations.CreateModel(
            name='Entrepreuners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('id_people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpoturapp.people')),
            ],
        ),
        migrations.CreateModel(
            name='programs_entrepreuners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_entrepreuner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpoturapp.entrepreuners')),
                ('id_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpoturapp.programs')),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='id_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpoturapp.types'),
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('id_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpoturapp.types')),
            ],
        ),
        migrations.CreateModel(
            name='people_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpoturapp.people')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpoturapp.users')),
            ],
        ),
        migrations.CreateModel(
            name='events_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpoturapp.events')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpoturapp.users')),
            ],
        ),
    ]
